spring:
  application:
    name: ruyuan-eshop-customer
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruyuan_eshop_customer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 18011
  redis:
    host: 47.102.157.169
    port: 6379
    password: 123456
    timeout: 3000

server:
  port: 8011

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.customer.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28091
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: ruyuan-eshop-customer,ruyuan-eshop-order

rocketmq:
  name-server: localhost:9876