spring:
  application:
    name: ruyuan-eshop-wms
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruyuan_eshop_wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 18008

server:
  port: 8008

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.wms.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28088
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
