spring:
  application:
    name: ruyuan-eshop-inventory
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruyuan_eshop_inventory?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 18001

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000

server:
  port: 8001

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.inventory.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28081
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: ruyuan-eshop-inventory

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: localhost:9876

#seata配置
seata:
  tx-service-group: ruyuan-eshop-inventory-group
  service:
    grouplist:
      ruyuan-eshop-seata: 127.0.0.1:8091
    vgroup-mapping:
      ruyuan-eshop-inventory-group: ruyuan-eshop-seata